# Generated by Django 3.0.6 on 2020-09-11 15:05

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='confess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subm_text', models.CharField(max_length=5000)),
                ('user', models.CharField(default='anonymous', max_length=100)),
                ('tagged_users', models.CharField(default='', max_length=100)),
                ('claps', models.IntegerField(default=0)),
                ('flags', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('post_muthalali', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme_author', models.CharField(default='anonymous', max_length=30)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('claps', models.IntegerField(default=0)),
                ('flags', models.IntegerField(default=0)),
                ('meme_caption', models.CharField(max_length=100)),
                ('meme_hub', models.CharField(default='TkmMemes', max_length=50)),
                ('meme_image', models.FileField(upload_to='Memes/images')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telegram_chat_id', models.IntegerField(default=0)),
                ('last_scene', models.DateTimeField(default=datetime.datetime(2018, 6, 15, 14, 0, 47, 552447))),
                ('online', models.CharField(default='False', max_length=5)),
                ('profile_icon', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pair', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='anonymous', max_length=100)),
                ('conf_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.confess')),
            ],
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='anonymous', max_length=100)),
                ('conf_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.confess')),
            ],
        ),
        migrations.CreateModel(
            name='memeflags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='anonymous', max_length=100)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.Memes')),
            ],
        ),
        migrations.CreateModel(
            name='memecomments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50)),
                ('comment_text', models.CharField(max_length=150)),
                ('comment_pub_date', models.DateTimeField(auto_now=True)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.Memes')),
            ],
        ),
        migrations.CreateModel(
            name='memeclaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='anonymous', max_length=100)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.Memes')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('comment_pub_date', models.DateTimeField(auto_now=True)),
                ('confess_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.confess')),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='unknown', max_length=30)),
                ('receiver', models.CharField(default='unknown', max_length=30)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('userpair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.UserPair')),
            ],
        ),
    ]
